# -*- coding: utf-8 -*-
"""LLM Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpfcoVa8OA62lnPFehG00pm-GuNvpP0i
"""

import kagglehub

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Automobile_data.csv')
df

def suggest_cars(df, preferences):
  filtered_df=df.copy()
  for key, value in preferences.items():
    if key in filtered_df.columns:
      filtered_df=filtered_df[filtered_df[key]==value]
      filtered_df=filtered_df.sort_values(by = 'price', ascending=True)
    return filtered_df

user_preferences={
    'fuel_type': 'gas',
    'body_style': 'sedan',
    'drive_wheels': 'fwd'
}
suggested_cars=suggest_cars(df, user_preferences)
print(suggested_cars[['make', 'fuel-type', 'body-style', 'drive-wheels','price']])